### ISSUE TITLE
Use anyMatch instead

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/GameSenseLib#1]
https://github.com/shaokeyibb/GameSenseLib/blob/c63e7b9f3014d163c97d94b88cf74d6babf30321/src/main/java/io/hikarilan/gamesenselib/flows/FlowManager.java#L94-L98

**Comment by shaokeyibb** [comment]
Thanks for your review!

The `Stream#anyMatch(Predicate<? super T>)` is "a short-circuiting terminal operation", that means if a flow return false, other flows can not continue to tick, that is doesn't meet our design guidelines of "do not relate to each other".
