### ISSUE TITLE
Use Predicate instead of Function<?, Boolean>

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/GameSenseLib#2]
https://github.com/shaokeyibb/GameSenseLib/blob/c63e7b9f3014d163c97d94b88cf74d6babf30321/src/main/java/io/hikarilan/gamesenselib/flows/Phase.java#L73

What you need is `Supplier<?>`. It accepts an argument and returns a boolean.   
For `Function<?,Boolean>` , there are more (un)boxing

**Comment by shaokeyibb** [comment]
Thanks for your review!

Actually, the `Supplier<T>` functional interface accept an argument and returns nothing, maybe you mean `Predicate<T>`?

Anyway, i will use the `Predicate<T>` instead of a `Function<T,Boolean>`, thanks for your suggestion!

**Comment by iceBear67** [comment]
yes i mean predicate
