### ISSUE TITLE
Introduce PhaseFactory instead of reusing Phase

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/GameSenseLib#3]
https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/flows/Phase.java#L32

Reusable objects are good only when you have many of them to initialize, which stresses GC.  
In your scenario, it just stresses developers because they have to implement their finalizers correctly, like writing C++ codes in Java.

**Comment by iceBear67** [comment]
The same problem as Module, Make a tradeoff by yourself.

**Comment by shaokeyibb** [comment]
Thanks for your suggestion!

There's a scenario that we must use such `Reusable` system —— a game can be relaunched as a new game. In that case, I'm sorry this may a better way to handle that.

**Comment by iceBear67** [comment]
maybe you dont like creating objects lol
