### ISSUE TITLE
Type parameters for AbstractPlayer can be applied to AbstractGame

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/GameSenseLib#4]
https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L36

https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L269

https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L226

https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L190

https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L157

https://github.com/shaokeyibb/GameSenseLib/blob/master/src/main/java/io/hikarilan/gamesenselib/games/AbstractGame.java#L144

Actually, in most of time, `AbstractPlayer` s' type are same, and it is unreasonable to support multiple types of player.

A `AbstractGame<P extends AbstractPlayer>` might be better than less-type-safer one

**Comment by shaokeyibb** [comment]
Thanks for your suggestion!

Actually, there do have the time `AbstractPlayer`'s type are not same: just imagine you have a game with `IngamePlayer`s and `ObservePlayer`s, that's why I need to design such APIs.
