### ISSUE TITLE
Consider using JetBrains annotations

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/GameSenseLib#5]
They have `ApiStatus.AvailableSince , Internal, NotNull, Contract` and IDEA integration(underline `@Internal` APIs for example), and these are useful for a java library.

Just a recommendation.

**Comment by shaokeyibb** [comment]
Thanks for your suggestion!

At this time, there's do have a Jetbrains Annotations libraries in the classpath of the plugin, but I can't find the `Internal` and `ApiStatus.AvailableSince` annotations you said.

Can you provide their full name, thanks?

<img width="189" alt="image" src="https://user-images.githubusercontent.com/25865657/210298746-30a89bcb-15b5-4e31-bb82-60831c5a4e24.png">

**Comment by iceBear67** [comment]
https://github.com/JetBrains/java-annotations

org.jetbrains.annotations.ApiStatus

**Comment by shaokeyibb** [comment]
Got it, idk why I use a super early version of jb-annotation :<
